name: doctor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.4
  recase: ^4.1.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  get: ^4.6.5
  intl: ^0.18.1
  cached_network_image: ^3.2.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    # - assets/anim/
    - assets/icons/
    - assets/images/
    - assets/logos/
    # - assets/sounds/
    # - assets/videos/

  fonts:

    - family: OutfitBold
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf

    - family: OutfitMedium
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf

    - family: OutfitRegular
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf

    - family: OutfitSemiBold
      fonts:
        - asset: assets/fonts/Outfit-SemiBold.ttf

